log/log/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logs.urls', namespace='logs')),
]

log/logs/urls.py
from django.urls import path

from . import views
app_name = 'logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

log/logs/models.py
from django.db import models

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries' 
    def __str__(self):
        return self.text[:50] + "..."

log/logs/views.py
from django.shortcuts import render
from .models import Topic
# Create your views here.
def index(request):
    topics = Topic.objects.order_by('-date_added')
    context = {
        'topics': topics,
        }
    return render(request,'logs/index.html', context)
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries,
        }
    return render(request,'logs/topic.html', context)

log/logs/templates/logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Суетимся</title>
    {%load static%}

    <link rel="stylesheet" type="text/css" href="%static'style.css'%">

</head>
<body>
    <div class="header">
        <p><a href="{% url 'logs:index' %}">
            Журнал записей пользователя
            </a></p>
        {%if user is authenitcated%}{{user.username}}{%endif%}
    </div>
    {% block content %}{% endblock content %}
</body>
</html>

log/logs/templates/logs/index.html
{% extends 'logs/base.html' %}

{% block content %}

<h3>Темы:</h3>

{% for topic in topics %}
<p>
<strong>
<a href="/topics/{{ topic.id }
{{topic.text}}
</a>
</strong>
(Дата создания: 
{{topic.date_added|dat
</p>
{% empty %}
<p style>Долгов</p>
<p>Григорьев</p>
<p>Алигберов</p>
<p>Борисов</p> 
{% endfor %}

{% endblock content %}

log/logs/templates/logs/topic.html
{% extends 'logs/base.html' %}

{% block content %}

<h3>Тема: {{topic}}</h3>

{% for entry in entries %}
<p>
{{entry.text|linebreaks}}
(Дата создания: {{entry.date_added|dat
</p>
{% empty %}
<p>Пока нет записей</p> 
{% endfor %}

{% endblock content %}